# Generated by Django 3.1.2 on 2020-11-06 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('checkout', '0003_auto_20201106_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_piid',
            new_name='stripe_pid',
        ),
        migrations.AddField(
            model_name='order',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='profiles.userprofile'),
        ),
    ]
